## Travis CI Script by Caio Oliveira aka Caio99BR <caiooliveirafarias0@gmail.com>
# For Open-PS2-Loader
## Thanks to:
# - izdubar@psx-scene and jimmikaelkael@psx-scene
#   <http://psx-scene.com/forums/f150/%5Blinux%5D-opl-compile-guides-63749/>
# - Bat Rastard@psx-scene and doctorxyz@psx-scene
#   <http://psx-scene.com/forums/f150/2015-linux-mint-vm-creation-opl-compiling-guide-ps2sdk-127047/index3.html#post1169435>
# - and a lot of people around internet :)

dist: trusty
sudo: required
language: c
cache: ccache

services:
  - docker

## Fix make_changelog.sh
git:
  depth: 9999999

before_install:
  ## Show things
  - ls -l

  ## Get docker image
  - docker pull akuhak/ps2toolchain
  - docker ps
  
  ## Save repo name
  - export NEW_REPO_SLUG=$(echo ${TRAVIS_REPO_SLUG} | cut -f 1 -d "/")

  ## Make CCache good to us
  - export PATH="/usr/lib/ccache:${PATH}"

  ## Show things again, please
  - ls -l

before_script:
  ## Run DOCKER, run!
  - docker run -d akuhak/ps2toolchain bash -c "while true; do sleep 5; done" > container_id

  ## Configure last things before build
  - docker exec -t $(cat container_id) bash -c "ls -l"
  - docker exec -t $(cat container_id) bash -c "cd /; git clone https://github.com/ps2dev/ps2sdk"
  # seems like ps2sdk again bad - try to checkout older commits
  - docker exec -t $(cat container_id) bash -c "cd /ps2sdk/; git checkout c6e6884d1eb51ca62ae848d0928554667a7a1816"
  - docker exec -t $(cat container_id) bash -c "cd /ps2sdk/; make --silent install"

  - docker exec -t $(cat container_id) bash -c "cd /; git clone https://github.com/ps2dev/ps2sdk-ports"
  - docker exec -t $(cat container_id) bash -c "cd /ps2sdk-ports/zlib/; make install"
  - docker exec -t $(cat container_id) bash -c "cd /ps2sdk-ports/libpng/; make install"
  - docker exec -t $(cat container_id) bash -c "cd /ps2sdk-ports/libjpeg/; make install"
  - docker exec -t $(cat container_id) bash -c "cd /ps2sdk-ports/freetype-2.4.12/; ./SetupPS2.sh"

  ## Set up the gsKit
  - docker exec -t $(cat container_id) bash -c "cd /; git clone https://github.com/ps2dev/gsKit /gsKit/"
  - docker exec -t $(cat container_id) bash -c "cd /gsKit/; make install"

  ## Set up the ps2packer
  - docker exec -t $(cat container_id) bash -c "cd /; git clone https://github.com/ps2dev/ps2-packer"
  - docker exec -t $(cat container_id) bash -c "cd /ps2-packer/; make; make install"

script:
  ## Go back to opl dir
  - docker exec -t $(cat container_id) bash -c "cd /; git clone https://github.com/AKuHAK/Open-PS2-Loader /Open-PS2-Loader/"

  ## BUG: If we not call './make_changelog.sh' before 'make', it will always
  ## build OPL with old REVISION, and make things confuse
  ##
  ## Make a new changelog
  - docker exec -t $(cat container_id) bash -c "cd /Open-PS2-Loader/; ./make_changelog.sh"

  ## Hack to prevent '-dirty' flag
  - docker exec -t $(cat container_id) bash -c "cd /Open-PS2-Loader/;git add -A"

  ## Let's build Open PS2 Loader Release!
  - docker exec -t $(cat container_id) bash -c "cd /Open-PS2-Loader/;make debug LOCALVERSION=${NEW_REPO_SLUG}"

  ## Make the lang pack
  - docker exec -t $(cat container_id) bash -c "cd /Open-PS2-Loader/; ./lng_pack.sh"

after_success:
  ## Upload the build
  - docker exec -t $(cat container_id) bash -c "export OPL_VERSION=$(make oplversion)"
  - docker exec -t $(cat container_id) bash -c "curl --upload-file /OPNPS2LD-${OPL_VERSION}-${NEW_REPO_SLUG}.ZIP https://transfer.sh/OPNPS2LD-${OPL_VERSION}-${NEW_REPO_SLUG}-NIGHTLY${TRAVIS_BUILD_NUMBER}.zip"
  #- docker exec -t $(cat container_id) bash -c "curl --upload-file /OPNPS2LD_LANGS-${OPL_VERSION}.zip https://transfer.sh/OPNPS2LD_LANGS-${OPL_VERSION}-NIGHTLY${TRAVIS_BUILD_NUMBER}.zip"
