
IOP_BIN = ds4bt.irx
IOP_OBJS = ds4bt.o imports.o
IOP_OBJS_DIR = obj.ds4bt/

IOP_CFLAGS += -DUSE_SMSUTILS

include $(PS2SDK)/Defs.make
include ../../Rules.bin.make
include $(PS2SDK)/samples/Makefile.iopglobal
