
IOP_BIN = xboxoneusb.irx
IOP_OBJS = xboxoneusb.o imports.o
IOP_OBJS_DIR = obj.xboxoneusb/

IOP_CFLAGS += -DUSE_SMSUTILS

include $(PS2SDK)/Defs.make
include ../../Rules.bin.make
include $(PS2SDK)/samples/Makefile.iopglobal
