
IOP_BIN = ds3bt.irx
IOP_OBJS = ds3bt.o imports.o
IOP_OBJS_DIR = obj.ds3bt/

IOP_CFLAGS += -DUSE_SMSUTILS

include $(PS2SDK)/Defs.make
include ../../Rules.bin.make
include $(PS2SDK)/samples/Makefile.iopglobal
