
IOP_BIN = hidusb.irx
IOP_OBJS = hidusb.o imports.o
IOP_OBJS_DIR = obj.hidusb/

IOP_CFLAGS += -DUSE_SMSUTILS

include $(PS2SDK)/Defs.make
include ../../Rules.bin.make
include $(PS2SDK)/samples/Makefile.iopglobal
