
IOP_BIN = ds4usb.irx
IOP_OBJS = ds4usb.o imports.o
IOP_OBJS_DIR = obj.ds4usb/

IOP_CFLAGS += -DUSE_SMSUTILS

include $(PS2SDK)/Defs.make
include ../../Rules.bin.make
include $(PS2SDK)/samples/Makefile.iopglobal
