IOP_BIN = smap-udpbd-mini.irx
IOP_OBJS = main.o ministack.o smap.o udpbd.o xfer.o imports.o

IOP_INCS += -I../../iopcore/common -I../common

include $(PS2SDK)/Defs.make
include ../../Rules.bin.make
include $(PS2SDK)/samples/Makefile.iopglobal
