
IOP_BIN = ds3usb.irx
IOP_OBJS = ds3usb.o imports.o
IOP_OBJS_DIR = obj.ds3usb/

IOP_CFLAGS += -DUSE_SMSUTILS

include $(PS2SDK)/Defs.make
include ../../Rules.bin.make
include $(PS2SDK)/samples/Makefile.iopglobal
