
IOP_BIN = btstack.irx
IOP_OBJS = btstack.o imports.o exports.o
IOP_OBJS_DIR = obj.btstack/

IOP_CFLAGS += -DUSE_SMSUTILS

include $(PS2SDK)/Defs.make
include ../../Rules.bin.make
include $(PS2SDK)/samples/Makefile.iopglobal
