
IOP_BIN = xbox360usb.irx
IOP_OBJS = xbox360usb.o imports.o
IOP_OBJS_DIR = obj.xbox360usb/

IOP_CFLAGS += -DUSE_SMSUTILS

include $(PS2SDK)/Defs.make
include ../../Rules.bin.make
include $(PS2SDK)/samples/Makefile.iopglobal
